# Params for Orca nodes (external odometry from uwlocalization)

manager:
  ros__parameters:
    mav_msg_ids: [31, 32]
    mav_msg_rate: 20

base_controller:
  ros__parameters:
    use_sim_time: true

    map_frame_id: "map"
    slam_frame_id: "slam"
    down_frame_id: "down"
    odom_frame_id: "odom"
    base_frame_id: "base_link"
    camera_frame_id: "left_camera_link"

    transform_expiration_ms: 0
