mavros:
  ros__parameters:
    use_sim_time: true
    system_id: 255
    target_system_id: 1
    target_component_id: 1

    plugin_allowlist:
      - sys_status
      - command
      - imu
      - local_position
      - odometry
      - vision_pose
      - setpoint_velocity
      - setpoint_raw
      - global_position
      - param

mavros_node:
  ros__parameters:
    use_sim_time: true
    fcu_url: "udp://0.0.0.0:14551@"
    gcs_url: ""

mavros/local_position:
  ros__parameters:
    frame_id: "map"
    tf:
      send: false

mavros/global_position:
  ros__parameters:
    frame_id: "map"
    tf:
      send: false

mavros/setpoint_velocity:
  ros__parameters:
    frame_id: "base_link"
    mav_frame: "BODY_NED"

mavros/imu:
  ros__parameters:
    frame_id: "base_link"

mavros/odometry:
  ros__parameters:
    in:
      frame_id: "odom"
      child_frame_id: "base_link"
      frame_tf:
        local_frame: "local_origin_ned"
        body_frame: "base_link"

mavros/vision_pose:
  ros__parameters:
    tf:
      listen: false
      frame_id: "map"
      child_frame_id: "base_link"